name = "url-shortener-dev"
type = "javascript"
account_id = "4ae2b0231430be3b4de63e32381d6513"
zone_id = "af76b9090f6e819df8e36ba0d850b2fd"
workers_dev = true
kv_namespaces = [
  { binding = "REDIRECTS", id = "a440b997322e4f74b64de848dee1d149", preview_id = "22e9d18085d44c049a481035df41c5b1" }
]

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[env.production]
name = "url-shortener"
workers_dev = false
routes = [
  "connect-with.vortex.name/*"
]
kv_namespaces = [
  { binding = "REDIRECTS", id = "d6444b81e4be4991af05e9cbbe0b48f1", preview_id = "6a76c5899d914da5851e6f31a074692a" }
]
